### ISSUE TITLE
Enhance funnel run

### ISSUE THREAD

**Issue by adamstruck** [ohsu-comp-bio/funnel#105]
- [x] stdin, stdout and stderr flags
- [x] variables file
- [x] command file
- [x] pretty print json with `--print` flag
- [x] sort flags logically, not alphabetically
- [x] task dependencies via `--wait`

**Comment by buchanae** [comment]
- [ ] parse flags from bash heredoc e.g.

```
funnel run 'md5 $FILE' <<TPL
  -c ubuntu
  --in FILE=~/input.txt
TPL
```

**Comment by buchanae** [comment]
These are in the help example
```
    --in pair1=file://~/pair1.fastq
    --in pair2=file://~/pair2.fastq
```

**Comment by buchanae** [comment]
Other ideas:
- [ ] `--contents` for TaskParameter.contents
- [ ] `--script` for loading the command string from a file

**Comment by buchanae** [comment]
- [ ] thorough examples on the website and in `funnel help`

**Comment by jbingham** [comment]
What does --stdin do? 

stdout and stderr are the bucket paths to where the Docker command's stdout and stderr should be written, right?

**Comment by buchanae** [comment]
> What does --stdin do?

It gets added to the input files, downloaded, and connected to the executor process's stdin

> stdout and stderr are the bucket paths to where the Docker command's stdout and stderr should be written, right?

Correct.

**Comment by jbingham** [comment]
Re stdin: do you have a real-world example where being able to do that is that useful?

**Comment by buchanae** [comment]
> Re stdin: do you have a real-world example where being able to do that is that useful?

No, it's supported mainly because it's part of TES Executors.

**Comment by buchanae** [comment]
#110 takes care of most of this. Still a little bit of cleanup work to do there.
