### ISSUE TITLE
Server returns 200 when you cancel a nonexistent task

### ISSUE THREAD

**Issue by adamstruck** [ohsu-comp-bio/funnel#178]
It should return 404

**Comment by buchanae** [comment]
As part of this, it would be nice if it also printed a confirmation when the task was canceled.

**Comment by adamstruck** [comment]
Right now it returns a [CancelTaskResponse](https://github.com/ga4gh/task-execution-schemas/blob/master/task_execution.proto#L437). Are you proposing we change that?  

I think the return code should be enough to signify whether or not the task was canceled successfully.

**Comment by buchanae** [comment]
> Right now it returns a CancelTaskResponse. Are you proposing we change that?

Yes. This is what I see:

```
buchanan01 smc-het (master)
funnel run -S http://funnel_server_1:8000 'sleep 60'
b62cjp33qt7n0d1vkeo0
buchanan01 smc-het (master)
funnel -S http://funnel_server_1:8000 task cancel b62cjp33qt7n0d1vkeo0
{

}
```

That's not a very nice CLI experience. It's just an empty JSON object, pretty-printed, but I only know that because I'm familiar with Funnel. "Successfully canceled" would be better.
