### ISSUE TITLE
Error <file>: is a directory

### ISSUE THREAD

**Issue by pditommaso** [ohsu-comp-bio/funnel#188]
I have a script running on Funnel on macOS running fine. However when I execute the same on Linux, the Funnel server returns the following error message:

```
runner               System error
error                read /home/pditommaso/projects/funnel/funnel-work-dir/b610qrilsmn6lr5ik0ug/work/index: is a directory
taskID               b610qrilsmn6lr5ik0ug
time                 2017-08-02T19:35:51+02:00
workerID             local-worker-f95ddeea-1196-41e9-75c1-60ace716d41d
```

**Comment by buchanae** [comment]
Could you include the task message? If you're using `funnel run` you can do `funnel run --print`

**Comment by buchanae** [comment]
Possibly you're not setting FileType: https://github.com/ga4gh/task-execution-schemas/blob/master/task_execution.proto#L105

**Comment by pditommaso** [comment]
Yes, I'm not setting that field. I didn't noticed it was mandatory. This opens a problem on our side, Nextflow doesn't have that information. It infers it at runtime.

**Comment by kellrott** [comment]
Now being discussed in https://github.com/ga4gh/task-execution-schemas/issues/76
