### ISSUE TITLE
storage/swift: env detection causes system error

### ISSUE THREAD

**Issue by buchanae** [ohsu-comp-bio/funnel#352]
```
local                System error
attempt              0
error                failed to config Swift storage backend: Timeout when reading or writing data
index                0
taskID               b8867r2rl6qjhvin3lhg
time                 2017-11-18T08:46:46-08:00
timestamp            2017-11-18T08:46:46.16705505-08:00
```

I think what's happening is that ApplyEnvironment() is trying to connect to swift, which doesn't exist, and it returns an error which fails the task.

**Comment by adamstruck** [comment]
Steps to reproduce?

**Comment by buchanae** [comment]
Have the `OS_` variables in your environment. Specifically, `OS_AUTH_URL` probably needs to point to an inaccessible endpoint (i.e. turn off your vpn). Then just run `funnel server run` and `funnel run 'echo hi'`

**Comment by buchanae** [comment]
If there are no `OS_` variables in the environment, it works without error.

**Comment by adamstruck** [comment]
I get the following with an unaccessible URL: 

```
local                System error
attempt              0
error                failed to config Swift storage backend: Post http://10.96.11.20:5000/v2.0/tokens: dial tcp 10.96.11.20:5000: getsockopt: connection refused
index                0
taskID               b886spfpbjg286raarjg
time                 2017-11-18T09:31:22-08:00
timestamp            2017-11-18T09:31:22.427677412-08:00
```

**Comment by adamstruck** [comment]
This error comes from the `Authenticate()` call.  Not sure if this is really a bug. Could be chalked up to incorrect configuration.

**Comment by buchanae** [comment]
The bug is that I was using the server with no swift config at all, and not reference to swift in my task.

**Comment by adamstruck** [comment]
So it is a side effect of having storage backends turned on by default.  Maybe the storage backends should only open connections during `Get` and `Put` calls?  The constructors then would just create the config / auth objects needed to make the connection.

**Comment by adamstruck** [comment]
Also providing no swift config currently implies that you are expecting the config to come from the environment.

**Comment by buchanae** [comment]
Ya, I like that idea. Less chance that config is going to mess with a task that doesn't even want that storage backend.
