### ISSUE TITLE
Mount read-only inputs into read-write directories

### ISSUE THREAD

**Issue by buchanae** [ohsu-comp-bio/funnel#36]
The status quo is that tools are expected to symlink files into a writable directory, to work around readonly input directories. Tools frequently forget to do this, and that will probably always be true. It also clogs up tools with symlinking code.

We could implement a simple feature that automatically creates a directory with those symlinks set up, which would save us time fixing tools, and save authors the trouble of symlinking input files.

**Comment by buchanae** [comment]
The automatic symlinking was a bad idea, but the problem exists. The best proposal so far is to mount read-only files inside read-write volumes via Docker e.g. `-v /host/path:/tmp:rw -v /host/path/file.txt:/host/path/file.txt:ro`

**Comment by adamstruck** [comment]
Based on the latest version of the spec each input will be mounted separately and all inputs are read-only. Addressed in #82
