### ISSUE TITLE
RPC error when trying to run funnel

### ISSUE THREAD

**Issue by prismofeverything** [ohsu-comp-bio/funnel#366]
local                error writing event
    error                rpc error: code = DeadlineExceeded desc = context deadline exceeded
    time                 2017-11-29T19:20:20Z

**Comment by adamstruck** [comment]
Events over RPC have a configurable timeout:
https://github.com/ohsu-comp-bio/funnel/blob/master/config/config.go#L269

Related to: https://github.com/ohsu-comp-bio/funnel/issues/275
