### ISSUE TITLE
cmd/task/list: --minimal --basic --full and also --view with lowercase name

### ISSUE THREAD

**Issue by buchanae** [ohsu-comp-bio/funnel#375]
As I explain list commands to users, I realize the view arguments are a little limited/quirky. I should have to say "it must be all caps", for example. And also, since I use these different views often, it'd be nice to have a shorthand for the views.

**Comment by adamstruck** [comment]
I think that making the view flag case insensitive is sufficient. I don't think we need the extra flags. 

https://github.com/ohsu-comp-bio/funnel/pull/372/commits/f7436d6acd83a7f0c2ffbcd232591b8238ea3f10

**Comment by buchanae** [comment]
An extra flag for all of them does seem like a mess. Perhaps a middle ground would be a `-f` flag for full? That's the one I use on almost all `task list` commands I run. I don't feel strongly about it though.

**Comment by buchanae** [comment]
After discussing this, we decided #372 was good enough, extra flags aren't needed.
