### ISSUE TITLE
worker: how to handle missing file on upload/download?

### ISSUE THREAD

**Issue by buchanae** [ohsu-comp-bio/funnel#387]
```
{
  "attempt": 0,
  "error": "open /mnt/funnel/b8lcpr33qt7m342cp7qg/mnt/nfs1/smc-het/working_dir/6401026/tasks/tumors/P8-noXY/5/tumor.tar.gz: no such file or directory",
  "index": 0,
  "level": "error",
  "msg": "System error",
  "nodeID": "funnel-worker-8-3",
  "ns": "worker",
  "taskID": "b8lcpr33qt7m342cp7qg",
  "time": "2017-12-08T13:23:55-08:00",
  "timestamp": "2017-12-08T13:23:55.932216785-08:00"
}
```

The event above is from a task which tried to upload a file that didn't exist. This task failed with state == SYSTEM_ERROR, which seems like the wrong state in this case. The system didn't fail, the task did.

Unfortunately, I just changed the TES spec to have EXECUTOR_ERROR instead of just ERROR... Now I wish I hadn't done that.

**Comment by buchanae** [comment]
Actually, download applies too. SYSTEM_ERROR implies that the system failed, but if you name an object to download that doesn't exist, the system isn't really failing, your task is.

**Comment by buchanae** [comment]
Note, it seems swift actually just ignores errors on directories during download when they don't exist:
![screen shot 2017-12-14 at 5 09 25 pm](https://user-images.githubusercontent.com/262647/34022017-afd66ca6-e0f1-11e7-8e0a-296190eb6116.png)

AFAICT, swift://smc-het/shared-tools does not exist.

**Comment by adamstruck** [comment]
Looking at the code (https://github.com/ohsu-comp-bio/funnel/blob/master/storage/swift.go#L81-L83) I am not surprised. Our prefix match call would return an empty slice rather than an error.

**Comment by adamstruck** [comment]
Proposed solution in #410:
* Upload / Download of files that do not exist results in an error
* Upload / Download of an empty directory results in a warning
* Upload of a nonexistent directory results in an error
