### ISSUE TITLE
worker: system error messages are duplicated

### ISSUE THREAD

**Issue by buchanae** [ohsu-comp-bio/funnel#389]
The symptom I'm seeing is that the logs have duplicate error messages, but one has less context:
<img width="681" alt="screen shot 2017-12-10 at 10 50 20 am" src="https://user-images.githubusercontent.com/262647/33808258-21a495b8-dd98-11e7-9d15-393d0e5f995e.png">

Not sure what the best solution is. We might consider dropping this line:
https://github.com/ohsu-comp-bio/funnel/blob/master/worker/worker.go#L71

**Comment by adamstruck** [comment]
Alternatives:
 - Drop the other `Event.Error` calls and make sure we put the context into the error message
 - Custom error type that the deferred function can use to determine whether or not it needs to generate an event.

**Comment by buchanae** [comment]
Meh. I'd rather the logs be a little noisy than add complexity and potentially bugs to fix this.
