### ISSUE TITLE
Support task dependency

### ISSUE THREAD

**Issue by jbingham** [ohsu-comp-bio/funnel#39]
During the earlier discussion of the TES spec, one idea was to add support for task dependency -- ie, run this task after this other task id completes. That got removed, or at least postponed. It would be a super useful feature though. All of the popular job schedulers -- SGE, Slurm, HTCondor -- support it, and for a reason.

Possible implementations:
- client side, in a command-line; we're doing this in dsub right now
- server side, with a new field in the TES payload

For the command-line, we're calling it --after taskId1[,taskId2,...]

**Comment by buchanae** [comment]
This is related to #38 and we're looking at building this into the funnel client CLI as `funnel wait` and `funnel run --wait`.

I'd be interested in learning about cases where handling this client-side isn't good enough though.

**Comment by buchanae** [comment]
#98 added `funnel run --wait` and `funnel wait`. #105 will further refine this.

I don't expect we'll be implementing this on the server side in the near future.

**Comment by jbingham** [comment]
Cases where client-side isn't ideal:

- Close laptop (have to run the client on a VM at addl cost)
- Complex graph where a blocking funnel task wastes cpu cycles (in theory, maybe not in practice)
- The backend already supports server-side dependency
- The backend can display DAGs only if the tasks are all submitted up-front without client-side blocking

That said, client-side is really not too bad :)

**Comment by buchanae** [comment]
Great, thanks for the insight. Being able to close your laptop seems important. Possibly we can do this on a per-backend basis: if the backend supports dependency, we can consider using it.

**Comment by buchanae** [comment]
I have some experimental task dependency code here, which might be a good starting point if we ever want to do this in Funnel: https://github.com/buchanae/ktl
