### ISSUE TITLE
storage/swift: panic

### ISSUE THREAD

**Issue by buchanae** [ohsu-comp-bio/funnel#459]
<img width="1336" alt="screen shot 2018-01-25 at 5 34 07 pm" src="https://user-images.githubusercontent.com/262647/35421093-13f36d36-01f6-11e8-88b0-e5353a6f3a51.png">

**Comment by adamstruck** [comment]
Looking at the storage backends I suspected we could trigger this sort of panic for all of the object store backends using a URL such as `swift://some-bucket`.
