### ISSUE TITLE
compute: Apache mesos

### ISSUE THREAD

**Issue by matthdsm** [ohsu-comp-bio/funnel#503]
Hi,

Are there any plans to support Apache Mesos/ Chronos for batch processing?

Thanks
M

**Comment by buchanae** [comment]
No plans, but we're interested in all compute backends.

**Comment by buchanae** [comment]
@matthdsm If you have experience with Mesos, we could use some advice/input on how you imagine it integrating with Funnel. We don't have experience with a Mesos in production yet.
