### ISSUE TITLE
examples/default-config: hpc backend templates use non-existent NodeId

### ISSUE THREAD

**Issue by buchanae** [ohsu-comp-bio/funnel#524]
https://github.com/ohsu-comp-bio/funnel/blob/master/config/default-config.yaml#L210

**Comment by adamstruck** [comment]
To clarify: this is just an issue in the default-config.yaml.  The actual default values do not use the NodeId template variable. 

Example: 
https://github.com/ohsu-comp-bio/funnel/blob/master/config/gridengine-template.txt#L2
