### ISSUE TITLE
FunnelEcsTaskRole needs DynamoDB CreateTable permissions

### ISSUE THREAD

**Issue by tom-dyar** [ohsu-comp-bio/funnel#579]
For some reason, during the first job run, I suppose tables were not present (failure during "create resources" command?) so they needed to be created? I edited the role in IAM and that got me past the error...

**Comment by buchanae** [comment]
Yes, we have some table creation code here, that runs during initialization:
https://github.com/ohsu-comp-bio/funnel/blob/master/database/dynamodb/util.go#L26

I guess this is at least a documentation issue, but we could also more during server start to present this error.

This is related to #496

**Comment by adamstruck** [comment]
The server creates the dynamodb tables if they don't already exist. Only workers should be using the FunnelEcsTaskRole so I don't think this is actually an issue.
