### ISSUE TITLE
Overriding Entrypoint

### ISSUE THREAD

**Issue by Jerdak** [ohsu-comp-bio/funnel#597]
Using the following task:

```
{
  "name": "Openssl Example",
  "description": "Non-Alpine test",
  "executors": [
    {
      "image": "frapsoft/openssl",
      "command": ["openssl", "list-standard-commands"],
       "stdout": "/tmp/out"
    }
  ]
}
```
I get the following error in my output:

```
openssl:Error: 'openssl' is an invalid command.
```

The problem seems to be the the `frapsoft/openssl` Dockerfile defaults to an ENTRYPOINT of `openssl`.    I know that I can remove `openssl` from my `command` and things will work but in a less contrived example I use that same Dockerfile for other commands, each of which `openssl` attempts to run.

Does funnel have a way to overwrite the `--entrypoint` flag of Docker run to something like an empty string so that Docker treats the everything after the image name as a command or is there something I'm missing.  Admittedly my docker-fu is rusty.

Funnel Version:

```
git branch: master
git upstream: 
build date: 2018-06-20T16:17:18Z
version: 0.8.0
```

Docker Version:

```
Docker version 18.06.1-ce, build e68fc7a
```

**Comment by buchanae** [comment]
There's no way to override the entrypoint. We've discussed adding that feature though.

The workaround for right now is to create a docker image that doesn't set the entrypoint. AFAICT, that's pretty straightforward: https://github.com/moby/moby/issues/3465#issuecomment-47598629

So basically:
```
FROM frapsoft/openssl
ENTRYPOINT []
```

**Comment by Jerdak** [comment]
@buchanae Makes sense.  I'll adjust accordingly, just double checking that I wasn't missing something obvious.
