### ISSUE TITLE
funnel server crashes

### ISSUE THREAD

**Issue by kmavrommatis** [ohsu-comp-bio/funnel#603]
Frequently the funnel server (v.0.8.0) crashes.
Initially the response of the web ui is very slow and eventually it crashes with the message on screen

The server is running either as a docker container, or on the host.
I am using AWS backend with DynamoDB.

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0xfd8d2a]

goroutine 8 [running]:
github.com/ohsu-comp-bio/funnel/compute/batch.(*Backend).reconcile(0xc42041a8c0, 0x16aeca0, 0xc42045bb80)
	/Users/buchanae/src/github.com/ohsu-comp-bio/funnel/compute/batch/backend.go:172 +0x3aa
created by github.com/ohsu-comp-bio/funnel/compute/batch.NewBackend
	/Users/buchanae/src/github.com/ohsu-comp-bio/funnel/compute/batch/backend.go:34 +0x264
```

**Comment by kellrott** [comment]
It's looking like the dynamo db listing is failing ( @adamstruck there is an unchecked error on https://github.com/ohsu-comp-bio/funnel/blob/master/compute/batch/backend.go#L166 ).
It sounds like as dynamo isn't scaling as the number of tracked jobs grows. How many jobs have populated the system at that point?

**Comment by kmavrommatis** [comment]
There are only a little over 300 jobs in the system, and the problem has started (less frequently at first) even when 20 or so jobs were in the system.
I have not tried to tweak anything for DynamoDB, but if the problem is on the DB interface I will probably follow the advice in  comment #602 and try try mongoDB (or perhaps AWS DocumentDB ?).

**Comment by kellrott** [comment]
Yeah, you should probably try the mongo based DB. We can fix the error check, so the server doesn't crash, but that won't fix the errors or the slow down that seem to be happening.

**Comment by adamstruck** [comment]
@kmavrommatis can you try again using the new 0.9.0 release?

**Comment by kmavrommatis** [comment]
@adamstruck 
It seems to be more stable. I did not have the chance to test it extensively, just run ~50ish tasks and still has not crashed.
I will keep working with it and let you know

**Comment by adamstruck** [comment]
@kmavrommatis glad to hear the server is more stable. Keep me posted.
