### ISSUE TITLE
running funnel server run shows Bad command "server". Bad command "run".

### ISSUE THREAD

**Issue by sunidhichaudhary** [ohsu-comp-bio/funnel#607]
if I run funnel it shows `Usage: funnel [|] [>[>]file] [|program] Version: 0.12a`
but if I run anything else like funnel version it shows Bad version.

**Comment by adamstruck** [comment]
Looks like you're calling a different program with the same name? Check your path variable.

**Comment by sunidhichaudhary** [comment]
I didn't understand, what do you mean by calling a different program with the same name?
My path variable is /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/local/go/bin:/home/sunidhi/go/bin

**Comment by adamstruck** [comment]
I meant that the usage message you posted is not from the funnel program in this repo. 

How did you install funnel?

**Comment by sunidhichaudhary** [comment]
I downloaded funnel from `https://ohsu-comp-bio.github.io/funnel/download/` page and did the following commands ```
brew tap ohsu-comp-bio/formula
brew install funnel
```
then it shows
`Warning: ohsu-comp-bio/formula/funnel 0.8.0 is already installed and up-to-date
To reinstall 0.8.0, run `brew reinstall funnel`
I also tried to build the latest developement by following commands
`$ mkdir -p $GOPATH/src/github.com/ohsu-comp-bio/
$ cd $GOPATH/src/github.com/ohsu-comp-bio/
$ git clone https://github.com/ohsu-comp-bio/funnel.git
$ cd funnel
$ make`
there comes an error when I tried to `make` that `dep : command not found` 
although I have installed dep.

**Comment by sunidhichaudhary** [comment]
I found the problem. The program was installed properly The command that I run is `./funnel server run `not `funnel server run` for make it to work properly.
