### ISSUE TITLE
Funnel in Docker Container

### ISSUE THREAD

**Issue by AlexanderSenf** [ohsu-comp-bio/funnel#634]
I have what feels like a beginner's question:

If I try to run Funnel inside of a Docker container, I end up with an error message `docker version command failed: exec: "docker": executable file not found in $PATH`. Which makes sense, if the Docker executable is not available inside of the container. However, I should be able to use the hist Docker installation - how do I need to configure this to work on a Mac?

Secondly: If I try to build the Dockerfile from Github I get error `The command '/bin/sh -c cd /go/src/github.com/ohsu-comp-bio/funnel && go build ./' returned a non-zero code: 1` at `Step 6/13 : RUN cd /go/src/github.com/ohsu-comp-bio/funnel && go build ./`

**Comment by adamstruck** [comment]
Should be fixed as of #635
