### ISSUE TITLE
PermissionDenied error when Basic Auth security is enabled

### ISSUE THREAD

**Issue by AlexanderSenf** [ohsu-comp-bio/funnel#640]
I was testing Funnel with the Basic Auth security settings uncommented. It seems to work well, any REST call to the API, or to the Web UI, requires authentication.

However, when I try to submit a task (using the basic `funnel examples hello-world > hello-world.json` example) to the API using something like (with 'User1':'abc123'):
```
curl -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' --header "Authorization: Basic dXNlcjE6YWJjMTIz" -d "@hello-world.json" 'http://localhost:8000/v1/tasks'
```
Then this results in an error:
```
{"error":"rpc error: code = PermissionDenied desc = ","event_data":{"SystemLog":{"msg":"failed to get task. ID unknown","level":"error","fields":{"error":"rpc error: code = PermissionDenied desc = "}}},"event_type":"SYSTEM_LOG","level":"error","msg":"error writing event","ns":"local","time":"2020-07-01T11:11:35Z"}
```
The same test without security works.

**Comment by adamstruck** [comment]
For 'User1': 'abc123' the header should be `Authorization: Basic VXNlcjE6YWJjMTIz`.

**Comment by AlexanderSenf** [comment]
Thanks for your quick response! I meant to write 'user1', the same user from the default-config.yaml file. This is the section specifying the user in my deployment:
```
                'BasicAuth': [
                    {"User": "user1", "Password": "abc123"}
                ],
```
This produces: `Authorization: Basic dXNlcjE6YWJjMTIz` 

But the point is that not that I can't access the API, that works very well. The `PermissionDenied` error is logged during task execution.

**Comment by adamstruck** [comment]
The funnel worker needs to be passed credentials in its config. 

https://ohsu-comp-bio.github.io/funnel/docs/security/basic/

```
RPCClient:
  User: funnel
  Password: abc123
```

**Comment by AlexanderSenf** [comment]
I have added that locally, and I can confirm it works now. Thank you!
