### ISSUE TITLE
Shared file system backend: don't localize input files

### ISSUE THREAD

**Issue by buchanae** [ohsu-comp-bio/funnel#7]
"localizing input files" means to copy/link task input files from their original location into a TES-managed job execution directory. This is similar to Cromwell behavior. Probably, this is done in order to simplify the process of mounting the input files into a Docker container – instead of mounting each file individually, you can just mount one directory containing all inputs.

Localizing files adds complexity to the code implementing TES, and possibly introduces some unwanted behavior, and we ( @adamstruck  and I) were debating whether it's necessary.

One example of unwanted behavior that I have run into in Cromwell is that if the execution directory and the original file live on different physical drives (e.g. the execution directory is an NFS mount, and the original file is on a local drive), then the input file cannot be hard linked and must be copied. This added some overhead to setting up jobs under Cromwell and is one of those non-obvious gotchas that could easily be missed and cause some degraded performance.

~~One important edge case to consider is: what if the input file is not on the shared file system? If the file isn't localized, then the file won't be correctly shared with the worker and the job would fail. Some configuration either in TES or in the client-side library could probably do some sanity checking to prevent this, by ensuring all input files are a child of the shared file system.~~

Originally:
https://github.com/bmeg/task-execution-server/issues/27

**Comment by buchanae** [comment]
> ~~One important edge case to consider is: what if the input file is not on the shared file system? If the file isn't localized, then the file won't be correctly shared with the worker and the job would fail. Some configuration either in TES or in the client-side library could probably do some sanity checking to prevent this, by ensuring all input files are a child of the shared file system.~~

This doesn't apply anymore, since Funnel is able to download/upload files from non-local storage systems (e.g. S3)

**Comment by adamstruck** [comment]
Related to #36.   I think this issue has been addressed.  As of #82, we mount in each input in read-only mode into the container.   Currently, we attempt to hard link all inputs into the task work dir prior to mounting. If the hard link fails we fall back to copy. 

The alternative would be to skip hardlinking/copying and mount the local files directly.
