### ISSUE TITLE
Upgrade TES

### ISSUE THREAD

**Issue by buchanae** [ohsu-comp-bio/funnel#70]
- [x] Simple renames
- [x] FileType enum
- [x] Volumes now repeated string
    - [x] infer volumes from outputs
    - [x] infer input volumes
- [x] Add TaskLog
    - [x] needs new database format
- [x] Volumes size in resources
- [x] remove read only volumes
- [x] remove jobID message
- [x] service info

New features:
- [x] environment variables
- [x] contents
- [x] store task tags
- [x] basic vs full task message
- [x] file log
- ~~[ ] list filtering on tags and state~~
- [x] paging?

**Comment by adamstruck** [comment]
First half completed in #82.  All new features still need to be implemented.

**Comment by adamstruck** [comment]
contents added in #124

**Comment by adamstruck** [comment]
Without paging its possible to exceed the max message size in the `ListTasks` endpoint. 

```
{"error":"grpc: trying to send message larger than max (6007841 vs. 4194304)","code":8}
```

Without imposing limits on the `contents` field in `Task` this could be a problem for the `CreateTask` and `GetTask` endpoints as well.

**Comment by buchanae** [comment]
I'm fine with requiring a single task message to be well under 4MB, how about you? We don't need to support massive scripts in `contents`

**Comment by adamstruck** [comment]
Sounds reasonable to me.  If anything I was thinking we should make MaxRecvMsgSize smaller than 4MB.   However, if we want to add a batch endpoint somewhere down the line we may need to reconsider this limit.
